# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326a0d870257eafe20938c38a408fc31460e2c0cff3e582d12ec756c9dc2d62c310bccaed647e08fab127e9a30c72447ca8a8fd18989843f1951d40d446d3e46

test:
  secret_key_base: cd15e47e5203e768c8838591a516216455b056c4aef9aa86e17b94bd9c4ace04608a2ca653560773f3e95e2f88ea27d1e820639e4d8e316052eeb6b24ad5ee0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
